Add complete step function
Idea-Pool/aws-testing-step-functions pull request #6
Opened 2023-07-19 13:31 UTC by kornel-filep

## What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Introduces the final SF to the CF Template.
Adds the necessary steps to the deployment script.
Adds the SNS Topic to the CF Template.

## What is the current behavior? (You can also link to an open issue here)
A basic step function is created in AWS.

## What is the new behavior (if this is a feature change)?
The planned step function is created in AWS. See the diagram in README.md

## Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
-

## Other information:
-

2023-07-20 08:48 UTC, szikszail requested changes
Just a small suggestion for the shell script

2023-07-20 08:48 UTC, szikszail commented on deploy.sh
> +stateDefinition=$(<aws/state-machine.asl.json)
```suggestion
stateDefinition=$(cat aws/state-machine.asl.json | tr -d '\n')
```

2023-07-20 08:48 UTC, szikszail commented on deploy.sh
> +sed -e "s/STATE_FUNCTION_ASL_JSON/$(echo $noNewLineStateDefinition)/" aws/cf-template.yml > aws/cf-template-tmp.yml
```suggestion
sed -e "s/STATE_FUNCTION_ASL_JSON/$stateDefinition/" aws/cf-template.yml > aws/cf-template-tmp.yml
```

2023-07-20 08:48 UTC, szikszail commented on deploy.sh
> +noNewLineStateDefinition=$(echo "$stateDefinition" | tr -d '\n')
```suggestion

```

2023-08-08 10:21 UTC, kornel-filep commented
thanks @szikszail, added the changes. tbh, forgot about this PR 😅

2023-08-08 10:30 UTC, szikszail approved these changes

2023-08-08 11:04 UTC, merged